[package]
name = "rocketclient"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.4"
uuid = "1.16.0"
flate2 = "1.1.1"
colored = "2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
fastnbt = "2"